FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY src ./src
COPY public ./public
COPY vite.config.js ./

ENV NODE_ENV=development
EXPOSE 5173

CMD ["npm", "run", "dev"]
